apiVersion: v1
kind: Secret
metadata:
  name: store-inventory-secrets
  labels:
    app: store
    service: inventory
    release: "1.2.0"
type: Opaque
stringData:
  DB_PASSWORD: "sup3r-s3cret-v3"
  API_KEY: "ak-rotated-7g8h9i"
