apiVersion: v1
kind: Service
metadata:
  name: store-inventory
  labels:
    app: store
    service: inventory
    release: "1.2.0"
spec:
  selector:
    app: store
    service: inventory
  ports:
    - port: 8080
      targetPort: 8080
