apiVersion: v1
kind: Secret
metadata:
  name: pay-payment-processor-secrets
  labels:
    app: payments
    service: payment-processor
    release: "1.2.0"
type: Opaque
stringData:
  PAYMENTS_SIGNING_KEY: "psk-v3"
  REGULATOR_KEY: "reg-v3"
