apiVersion: v1
kind: Service
metadata:
  name: pay-payment-processor
  labels:
    app: payments
    service: payment-processor
    release: "1.2.0"
spec:
  selector:
    app: payments
    service: payment-processor
  ports:
    - port: 8080
      targetPort: 8080
