apiVersion: v1
kind: Service
metadata:
  name: pay-ledger
  labels:
    app: payments
    service: ledger
    release: "1.2.0"
spec:
  selector:
    app: payments
    service: ledger
  ports:
    - port: 8080
      targetPort: 8080
