apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "example-service.fullname" . }}
  labels:
    {{- include "example-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "example-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "example-service.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "example-service.serviceAccountName" . }}
      containers:
        - name: example-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
